spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/score
    username: root
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

    database: mysql
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8b17f5e6120af126b2b89855e487272f
            client-secret: hbiqdrg7rkV0h8X4ocPDHZGimHkgvnOn
            redirect-uri: http://localhost:8080/app/login/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
          google:
            client-id: NaN
            client-secret: NaN
            scope:
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace

server:
  address: localhost
  port: 8080

##카카오 로그인 설정
#kakao:
#  client:
#    secret: hbiqdrg7rkV0h8X4ocPDHZGimHkgvnOn
#    id: 8b17f5e6120af126b2b89855e487272f
#  redirect:
#    url: http://localhost:8080/app/login/kakao